# -*- coding: utf-8 -*-
"""ahp_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzEQTKkn6SrEskl6zZg2FfMrPfvi3BU_
"""

# @title
!python -m pip install ahpy

!python -m pip install unidecode

"""#Bibliotecas"""

import ahpy
import itertools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import locale
from copy import copy
from unidecode import unidecode
from sklearn.linear_model import LinearRegression

"""#Funções"""

# Adiciona um valor muito baixo (epsilon) em valores que possuem zero
def tratamento_zeros1(df):
  epsilon = 0.0001

  # Percorrendo cada coluna
  for column in df.columns:
      # Apenas colunas numéricas (sem string, objeto)
      if df[column].dtype != object:
          # Retorna uma serie informando quais linhas, a coluna 'column' possui zero
          zeros_mask = (df[column] == 0)
          # Verifica se tem algum valor zero e adiciona o epsilon
          if zeros_mask.any():
              df.loc[zeros_mask, column] += epsilon

# Adiciona um valor muito baixo (epsilon) para todas as colunas
def tratamento_zeros2(df):
  epsilon = 0.0001
  for column in df.columns:
    if df[column].dtype != object:
      df[column] += epsilon

# Normaliza valores entre 1 e 9 (julgamentos de Saaty)
def normalize(values):
  min_val = min(values)
  max_val = max(values)
  normalized_values = []
  for val in values:
    normalized_val = ((val - min_val) / (max_val - min_val)) * 8 + 1
    normalized_values.append(normalized_val)
  return normalized_values

# Se for bom, inverse=False, se for ruim, inverse=True
# Pega uma lista de valores
# (por exemplo, os valores de um critério, os valores de uma coluna)
# e gera outra lista representando os valores de uma matriz de julgamentos
def julgamentos_alternativa(normalized_values, inverse):
  combinations_list = []
  if (inverse):
    for i, j in itertools.combinations(range(len(normalized_values)), 2):
      combinations_list.append(normalized_values[j] / normalized_values[i])
  else:
    for i, j in itertools.combinations(range(len(normalized_values)), 2):
      combinations_list.append(normalized_values[i] / normalized_values[j])
  return combinations_list

# Arredonda os valores da lista que representa os valores da matriz de julgamentos
# gerados pela função 'julgamentos_alternativa'
# O arredondamento reflete a escala Saaty
def arredonda_lista(lista,referencia):
  lista_arredondado = []
  for valor in lista:
    if valor >= 1:
      lista_arredondado.append(round(valor))
    else:
      diferenca_minima = float('inf')
      divisor_proximo = 0
      for divisor in referencia:
        diferenca = abs(valor - divisor)
        if diferenca < diferenca_minima:
          diferenca_minima = diferenca
          divisor_proximo = divisor
      lista_arredondado.append(divisor_proximo)
  return lista_arredondado

# Gera o dicionario dos julgamentos , utilizando uma lista das alternativas ou critérios
def gera_dicionario_julgamentos(chave, julgamentos):
  chave_pares = list(itertools.combinations(chave, 2))
  dic_julgamentos = dict(zip(chave_pares, julgamentos))
  return dic_julgamentos

# Automatiza o processo de calcular as prioridades locais das alternativas
# referente a cada critério
#def julgamentos_coluna(df,coluna,precision,municipios):
 # valores_col = df[coluna].values
  #valores_col = normalize(valores_col)

  #nome = coluna.split('-')[0]
  #inverter = coluna.split('-')[1]

  #if inverter=='bom':
   # julgamentos = julgamentos_alternativa(valores_col, inverse=False)
  #elif inverter=='ruim':
   # julgamentos = julgamentos_alternativa(valores_col, inverse=True)
  #else:
   # return 'ERRO'

  #julgamentos = arredonda_lista(julgamentos,REFERENCIA)
  #dict_julg = gera_dicionario_julgamentos(municipios, julgamentos)
  #replace_zero_values(dict_julg)
  #return ahpy.Compare(name=nome, comparisons=dict_julg, precision=precision, random_index='dd')

# Define a função patched__build_matrix (como antes)
from unittest.mock import patch  # Importa a função patch

@patch('ahpy.ahpy.Compare._build_matrix')
def patched__build_matrix(self, original__build_matrix):
    self._matrix = np.zeros((len(self._elements), len(self._elements)))
    for pair, value in self._pairs.items():
        location = tuple(self._elements.index(elements) for elements in pair)
        self._matrix[location] = value


def julgamentos_coluna(df, coluna, precision, municipios):
    valores_col = df[coluna].values
    valores_col = normalize(valores_col)

    nome = coluna.split('-')[0]
    inverter = coluna.split('-')[1]

    if inverter == 'bom':
        julgamentos = julgamentos_alternativa(valores_col, inverse=False)
    elif inverter == 'ruim':
        julgamentos = julgamentos_alternativa(valores_col, inverse=True)
    else:
        return 'ERRO'

    julgamentos = arredonda_lista(julgamentos, REFERENCIA)
    dict_julg = gera_dicionario_julgamentos(municipios, julgamentos)
    replace_zero_values(dict_julg)

    # Aplica o patch antes de criar a instância de ahpy.Compare
    with patch('ahpy.ahpy.Compare._build_matrix', patched__build_matrix):
        return ahpy.Compare(name=nome, comparisons=dict_julg, precision=precision, random_index='dd')

# Encontra os pares de alternativas onde não existe julgamento (valor 0)
# e remove estes pares
# Obs: O algoritmo da Biblioteca consegue lidar com pares faltantes
def remove_zero_values(dictionary):
    keys_to_remove = [key for key, value in dictionary.items() if value == 0]
    for key in keys_to_remove:
        del dictionary[key]

# Encontra os pares de alternativas onde não existe julgamento (valor 0)
# e substitui por um julgamento equivalente (valor 1)
def replace_zero_values(dictionary):
    for key, value in dictionary.items():
        if value == 0:
            dictionary[key] = 1

def normalize_dict(data_dict):
  min_value = min(data_dict.values())
  max_value = max(data_dict.values())

  normalized_dict = {k: (v - min_value) / (max_value - min_value) for k, v in data_dict.items()}
  return normalized_dict

def gera_excel_ranking(target_weights,nome):
  ranking = pd.DataFrame.from_dict(target_weights, orient='index', columns=['Cidade'])
  ranking.reset_index(inplace=True)
  ranking.columns = ['Cidade','Valor']
  nome_arquivo = f'ranking_{nome}.xlsx'
  ranking.to_excel(nome_arquivo, sheet_name=nome, index=False)

###def ordena_prioridades_alternativas(prioridades_alternativas):
 # prioridades = []
  #for i in range(0,len(prioridades_alternativas)):
  #  prioridades.append(dict(sorted(prioridades_alternativas[i].local_weights.items())))
 # return prioridades

def ordena_prioridades_alternativas(prioridades_alternativas):
  prioridades = []
  for i in range(0,len(prioridades_alternativas)):
    # Convert keys to strings before sorting
    local_weights_str_keys = {str(k): v for k, v in prioridades_alternativas[i].local_weights.items()}
    prioridades.append(dict(sorted(local_weights_str_keys.items()))) # Sort based on string keys
  return prioridades

def calculo_prioridade_global(variaveis_consumo,prioridade_criterio, prioridades_alternativas):
  ranking = []
  for key in prioridades_alternativas[0]:
    valor = 0
    for i,crit in enumerate(variaveis_consumo):
      if (key=='Águas de São Pedro'):
          print(f'PLAC{i}:{prioridades_alternativas[i][key]}, PC{crit}{prioridade_criterio[crit]}')


      valor += prioridades_alternativas[i][key]*prioridade_criterio[crit]
    if (key=='Monte Alegre do Sul'):
      print(f'VV{valor}')
    ranking.append(valor)

  return ranking

def coleta_objetos_por_categoria(lista_objetos, categorias):
  objetos = []
  for obj in lista_objetos:
    if obj.name in categorias:
      objetos.append(obj)
  return objetos

"""#Julgamento dos Critérios"""

from google.colab import drive
drive.mount('/content/drive')

crit = pd.read_excel('/content/drive/MyDrive/AHPY_IC_2025/análise de dados/preferencias_final.xlsx', sheet_name='criterios')
crit = crit.drop(crit.columns[0], axis=1)
crit

julg_crit = tuple(crit.values[np.triu_indices_from(crit.values, k=1)])
julg_crit

dict_julg_crit = gera_dicionario_julgamentos(crit.columns, julg_crit)
dict_julg_crit

global PRECISION
PRECISION = 4

#global CRITERIA
#CRITERIA = ahpy.Compare('Criteria', dict_julg_crit, precision=10, random_index='dd')
#CRITERIA.local_weights

from unittest.mock import patch  # Importa a função patch

@patch('ahpy.ahpy.Compare._build_matrix')
def patched__build_matrix(self, original__build_matrix):
    # Inicializa _matrix como uma matriz NumPy com zeros
    self._matrix = np.zeros((len(self._elements), len(self._elements)))
    for pair, value in self._pairs.items():
        location = tuple(self._elements.index(elements) for elements in pair)
        self._matrix[location] = value  # Usa indexação direta

with patch('ahpy.ahpy.Compare._build_matrix', patched__build_matrix):
    CRITERIA = ahpy.Compare('Criteria', dict_julg_crit, precision=10, random_index='dd')

CRITERIA.local_weights

def add_dictionary_values(dictionary):
    result = 0
    for value in dictionary.values():
        result += value
    return result

add_dictionary_values(CRITERIA.local_weights)

# @title
print("Indice de consistência do julgamento dos critérios: ", CRITERIA.consistency_ratio)

"""#Julgamento das alternativas"""

df = pd.read_excel('/content/drive/MyDrive/AHPY_IC_2025/análise de dados/preferencias_final.xlsx', sheet_name='dados2022_geral')
df

df_acentuado = df.copy()

df_acentuado[df_acentuado["Município"]=="Águas de São Pedro"]

df_acentuado.head(76)

df['Município'] = df['Município'].apply(lambda x: unidecode(x) if isinstance(x, str) else x)
df

tratamento_zeros1(df)

global MUNICIPIOS_ACENTUADO
MUNICIPIOS_ACENTUADO = tuple(df_acentuado['Município'].values)
global MUNICIPIOS
MUNICIPIOS = tuple(df['Município'].values)
global REFERENCIA
REFERENCIA = [1/i for i in range(1,10)]
global MAP
MAP = {}

for i in range(min(len(MUNICIPIOS), len(MUNICIPIOS_ACENTUADO))):
  MAP[MUNICIPIOS[i]] = MUNICIPIOS_ACENTUADO[i]
MAP

# @title
MUNICIPIOS_ACENTUADO

#global objetos_comp
#objetos_comp = []
#for column in df.iloc[:,9:].columns:
  #objetos_comp.append(julgamentos_coluna(df=df,coluna=column,precision=10,municipios=MUNICIPIOS))

global objetos_comp
objetos_comp = []
for column in df.iloc[:,9:].columns:
  if isinstance(column, str) and '-' in column:  # Only process columns containing '-' and of type string
    objetos_comp.append(julgamentos_coluna(df=df,coluna=column,precision=10,municipios=MUNICIPIOS))

global VARIAVEIS
VARIAVEIS = list(crit.columns)
VARIAVEIS

CRITERIA.global_weights

for obj in objetos_comp:
    print(type(obj), obj)  # Verifica os tipos e conteúdos

def calculo_prioridade_global(variaveis_consumo, prioridade_criterio, prioridades_alternativas):
    ranking = []
    for key in prioridades_alternativas[0]:
        valor = 0
        for crit, prioridade_dict in zip(variaveis_consumo, prioridades_alternativas):
            if key == 'Águas de São Pedro':
                print(f'{crit}: {prioridade_dict[key]} * {prioridade_criterio[crit]}')

            valor += prioridade_dict[key] * prioridade_criterio[crit]

        if key == 'Monte Alegre do Sul':
            print(f'Valor total: {valor}')
        ranking.append(valor)

    return ranking

prioridades_alt = ordena_prioridades_alternativas(objetos_comp)
ranking = calculo_prioridade_global(VARIAVEIS, CRITERIA.global_weights, prioridades_alt)
ranking_final = dict(zip(MUNICIPIOS_ACENTUADO,ranking))
ranking_final = dict(sorted(ranking_final.items(), key=lambda item: item[1], reverse=True))
ranking_final

norm_ranking_final = normalize_dict(ranking_final)
norm_ranking_final

gera_excel_ranking(norm_ranking_final,'rodada_1')

#baixar ranking xlsx
#from google.colab import files
#files.download('ranking_rodada_1.xlsx')

"""#Tipologias

# A
"""

df.columns

df_tip_A = df[df['Tipologia'] == 'A']
df_tip_A

municipios_A = tuple(df_tip_A['Município'].values)
objetos_comp_A = []
for column in df_tip_A.iloc[:,9:].columns:
  if isinstance(column, str) and '-' in column:  # Only process columns containing '-'
      objetos_comp_A.append(julgamentos_coluna(df_tip_A,column,precision=10,municipios=municipios_A))

prioridades_alt = ordena_prioridades_alternativas(objetos_comp_A)
ranking_A = calculo_prioridade_global(VARIAVEIS, CRITERIA.global_weights, prioridades_alt)
ranking_final_A = dict(zip(sorted(municipios_A),ranking_A))
ranking_final_A = dict(sorted(ranking_final_A.items(), key=lambda item: item[1], reverse=True))
ranking_final_A

new_rf = {}
for k,v in ranking_final_A.items():
  new_rf[MAP[k]] = v
new_rf

norm_ranking_final_A = normalize_dict(new_rf)
norm_ranking_final_A

#gera_excel_ranking(norm_ranking_final_A,'tip_A')
#files.download('ranking_tip_A.xlsx')

"""# B"""

df_tip_B = df[df['Tipologia'] == 'B']
df_tip_B

municipios_B = tuple(df_tip_B['Município'].values)
objetos_comp_B = []
for column in df_tip_B.iloc[:,9:].columns:
  if isinstance(column, str) and '-' in column:  # Only process columns containing '-'
      objetos_comp_B.append(julgamentos_coluna(df_tip_B,column,precision=10,municipios=municipios_B))

prioridades_alt = ordena_prioridades_alternativas(objetos_comp_B)
ranking_B = calculo_prioridade_global(VARIAVEIS, CRITERIA.global_weights, prioridades_alt)
ranking_final_B = dict(zip(sorted(municipios_B),ranking_B))
ranking_final_B = dict(sorted(ranking_final_B.items(), key=lambda item: item[1], reverse=True))
ranking_final_B

new_rf = {}
for k,v in ranking_final_B.items():
  new_rf[MAP[k]] = v
new_rf

norm_ranking_final_B = normalize_dict(new_rf)
norm_ranking_final_B

#gera_excel_ranking(norm_ranking_final_B,'tip_B')
#files.download('ranking_tip_B.xlsx')

"""# C"""

df_tip_C = df[df['Tipologia'] == 'C']

municipios_C = tuple(df_tip_C['Município'].values)
objetos_comp_C = []
for column in df_tip_C.iloc[:,9:].columns:
  if isinstance(column, str) and '-' in column:  # Only process columns containing '-'
    objetos_comp_C.append(julgamentos_coluna(df_tip_C,column,precision=10,municipios=municipios_C))

prioridades_alt = ordena_prioridades_alternativas(objetos_comp_C)
ranking_C = calculo_prioridade_global(VARIAVEIS, CRITERIA.global_weights, prioridades_alt)
ranking_final_C = dict(zip(sorted(municipios_C),ranking_C))
ranking_final_C = dict(sorted(ranking_final_C.items(), key=lambda item: item[1], reverse=True))
ranking_final_C

new_rf = {}
for k,v in ranking_final_C.items():
  new_rf[MAP[k]] = v
new_rf

norm_ranking_final_C = normalize_dict(new_rf)
norm_ranking_final_C

#gera_excel_ranking(norm_ranking_final_C,'tip_C')
#files.download('ranking_tip_C.xlsx')

"""# D"""

df_tip_D = df[df['Tipologia'] == 'D']

municipios_D = tuple(df_tip_D['Município'].values)
objetos_comp_D = []
for column in df_tip_D.iloc[:,9:].columns:
  if isinstance(column, str) and '-' in column:  # Only process columns containing '-'
    objetos_comp_D.append(julgamentos_coluna(df_tip_D,column,precision=10,municipios=municipios_D))

prioridades_alt = ordena_prioridades_alternativas(objetos_comp_D)
ranking_D = calculo_prioridade_global(VARIAVEIS, CRITERIA.global_weights, prioridades_alt)
ranking_final_D = dict(zip(sorted(municipios_D),ranking_D))
ranking_final_D = dict(sorted(ranking_final_D.items(), key=lambda item: item[1], reverse=True))
ranking_final_D

new_rf = {}
for k,v in ranking_final_D.items():
  new_rf[MAP[k]] = v
new_rf

norm_ranking_final_D = normalize_dict(new_rf)
norm_ranking_final_D

#gera_excel_ranking(norm_ranking_final_D,'tip_D')
#files.download('ranking_tip_D.xlsx')

"""# Análise Estatística"""

data_to_plot = [df_tip_A['IN049_AE-ruim'], df_tip_B['IN049_AE-ruim'], df_tip_C['IN049_AE-ruim'], df_tip_D['IN049_AE-ruim']]

# Creating the boxplot
plt.figure(figsize=(10, 6))
plt.boxplot(data_to_plot, patch_artist=True)

# Adding titles and labels
plt.title('Índice de perda na distribuição (IN049) de diferentes tipologias')
plt.xlabel('Tipologia')
plt.ylabel('Porcentagem')
plt.xticks([1, 2, 3, 4], ['A', 'B', 'C', 'D'])

# Show plot
plt.show()

data_to_plot = [df_tip_A['IN055_AE-bom'], df_tip_B['IN055_AE-bom'], df_tip_C['IN055_AE-bom'], df_tip_D['IN055_AE-bom']]

# Creating the boxplot
plt.figure(figsize=(10, 6))
plt.boxplot(data_to_plot, patch_artist=True)

# Adding titles and labels
plt.title('Índice de atendimento total de água (IN055) de diferentes tipologias')
plt.xlabel('Tipologia')
plt.ylabel('Porcentagem')
plt.xticks([1, 2, 3, 4], ['A', 'B', 'C', 'D'])

# Show plot
plt.show()

"""Natureza Jurídica"""

df_nat_sociedade = df[df['Natureza Jurídica'] == 'Sociedade de economia mista com administração pública']
df_nat_sociedade

df_nat_autarquia = df[df['Natureza Jurídica'] == 'Autarquia']

df_nat_adm = df[df['Natureza Jurídica'] == 'Administração pública direta']

df_nat_empresa = df[df['Natureza Jurídica'] == 'Empresa privada']

data_to_plot = [df_tip_A['IN055_AE-bom'], df_tip_B['IN055_AE-bom'], df_tip_C['IN055_AE-bom'], df_tip_D['IN055_AE-bom']]

# Creating the boxplot
plt.figure(figsize=(10, 6))
plt.boxplot(data_to_plot, patch_artist=True)

# Adding titles and labels
plt.title('Índice de atendimento total de água (IN055) de diferentes tipologias')
plt.xlabel('Tipologia')
plt.ylabel('Porcentagem')
plt.xticks([1, 2, 3, 4], ['A', 'B', 'C', 'D'])

# Show plot
plt.show()

