name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}   # projetocloud.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}                   # projetocloud
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t projetocloud.azurecr.io/ranking-app:latest .
          docker push projetocloud.azurecr.io/ranking-app:latest 
